### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by radiegtya** [usefulio/meteor-sync-methods#2]
//ON SERVER
Meteor.syncMethods({
    getAllAccounts: function(criteria, sort, callback) {
        var response =  Accounting.Accounts.find(criteria, sort).fetch();
        callback(err, response); //what should i do with this callback? and what should I return?
    },
});

//ON CLIENT
return Meteor.call("Accounting.Accounts.find", criteria, {sort: {code: 1}});  

Above code are not working. Thanks

**Comment by ianserlin** [comment]
You don't need to use this package anymore - just use `Meteor.wrapAsync`.

-------
Ian Serlin
ian@ianserlin.com
415-754-9563
http://twitter.com/spiceninja
http://www.linkedin.com/in/ianserlin

**Comment by Testato** [comment]
Meteor.wrapAsync is not simple like your Meteor.syncMethods 

I tryed Meteor.syncMethods on last Meteor 1.3.2.4 but it do not work.
Are you tried on last Meteor ?

**Comment by ianserlin** [comment]
I take a look at making it compatible, thanks for the report!

**Comment by ianserlin** [comment]
Ok, version `0.2.0` has been published to atmosphere that supports Meteor 1.3x +. Cheers!

**Comment by Testato** [comment]
confirmed that works, thanks a lot
this syncMethods should been officially in Meteor :-)

**Comment by mesameen** [comment]
Meteor.methods({

getSession: function() {
var session = Session.findOne({_id:'abc'});
if(session !== undefined){
var sessionId = session._id;
return sessionId;
}
}

});

Hi @Testato , My scenario is also like yours.

Can you help me to figure it out, how to use syncMethods?

I would like to make above method can be accessible one user at a time(means synchronous).

**Comment by Testato** [comment]
If you look in a closed issue of this repo you will found an example.
Also in the homepage of this repo is there two examples.
You may add the callback

**Comment by mesameen** [comment]
All the available examples are prior to 1.x, After this issues only released compatible to 1.3.x .
I think specifically relate to your issue. My issue is also like yours only. So, I asked yours. I tried with multiple ways by using Meteor.syncMethods as per my problem description but didn't succeed.
The available example is getting response from outside of application. But my scenario is not like that.
I have to take data from DB, validate and send to client. It is somewhat critical. Could you help me out.

Thanks for your reply. :-)

**Comment by Testato** [comment]
Sorry but i do not opened any issue.
I only tested the examples that i telled you, and all work whit this new 2.0 update

**Comment by mesameen** [comment]
Thankyou @Testato .

Can you help me to figure it out @radiegtya ,

Meteor.methods({

getSession: function() {
var session = Session.findOne({_id:'abc'});
if(session !== undefined){
var sessionId = session._id;
return sessionId;
}
}

});

Hi @radiegtya @ianserlin , My scenario is also like yours.

Can you help me to figure it out, how to use syncMethods?

I would like to make above method can be accessible one user at a time(means synchronous).

**Comment by ianserlin** [comment]
@sandeepmeenuga This package only makes it so that you can return the result of an asynchronous server method call "synchronously" for an individual client. It really doesn't have anything to do with only allowing a server method to be called "serially" by one client at a time. You'll need to write your own acquire/call/release locking mechanism for that.

**Comment by mesameen** [comment]
Thank you for your reply @ianserlin ,

I would like to avoid race condition while clicking two users one button at a time.
Basically I am a Java developer, so I thought synchronous(Thread) is the only way to do these type of tasks.
In this scenario will Meteor.wrapAsync give any effort?

Can you suggest any way to avoid race condition, if you aware?

:-)

**Comment by ianserlin** [comment]
@sandeepmeenuga I think I understand what you want (in previous lives I've written things like OpenFire in Java). You're going to want to search npmjs.org for something like `concurrency` or `locks` and then probably use that library in your Meteor project. `Meteor.wrapAsync` will have the same problem for you, it only allows you to write synchronous looking code around an asynchronous function _per user_.

Under the hood, both this library and `Meteor.wrapAsync` use `fibers` for achieving fake multi-threadedness in javascript, which is single-threaded by default.

**Comment by mesameen** [comment]
http://stackoverflow.com/questions/18170450/what-is-the-meteor-concurrency-model

In Meteor, your server code runs in a single thread per request, not in the asynchronous callback style typical of Node. We find the linear execution model a better fit for the typical server code in a Meteor application.
http://docs.meteor.com/#structuringyourapp

I found it @ianserlin , Can i go a head with this info.?

**Comment by ianserlin** [comment]
The key part of that is `single thread per request`, e.g. per user.

This is a better question to ask on the forums (forums.meteor.com) than here. :) Good luck!
